version: '2'
services:

  api:
    image: matheusmoreti/compose_api
    ports:
      - "4000:5000"
    links:
      - mysql
    depends_on:
      - mysql
    deploy:
      replicas: 3
      #update_config:
      #  parallelism: 1
      #  delay: 10is
      mode: replicated
      restart_policy:
        condition: on-failure
  mysql:
    image: matheusmoreti/compose_mysql
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: senhaFiap
       MYSQL_USER: root
       MYSQL_DATABASE: projetoDC
      deploy:
      replicas: 1
      # resources:
      #   limits:
      #     cpus: "0.1"
      #     memory: 50M
      restart_policy:
        condition: on-failure
